# Generated by Django 4.1.7 on 2023-04-16 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='CarBrand',
        ),
        migrations.DeleteModel(
            name='CarModel',
        ),
    ]
